export const ADD_TODO = 'ADD_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const EDIT_TODO = 'EDIT_TODO'
export const EDIT_TODO_DATE = 'EDIT_TODO_DATE'
export const COMPLETE_TODO = 'COMPLETE_TODO'
export const COMPLETE_ALL_TODOS = 'COMPLETE_ALL_TODOS'
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED'
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'
export const TODOS_TO_DO = 'TODOS_TO_DO'
export const TODOS_DONE = 'TODOS_DONE'
export const ALL_TODOS = 'ALL_TODOS'

  